// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c6602bf7-e304-4395-973e-245b17729274";

const char SSID[]               = SECRET_SSID;    
const char PASS[]               = SECRET_OPTIONAL_PASS;    
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    

void onLedChange();
void onLed2Change();
void onServoChange();

bool led;
bool led2;
bool servo;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(led2, READWRITE, ON_CHANGE, onLed2Change);
  ArduinoCloud.addProperty(servo, READWRITE, ON_CHANGE, onServoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
